//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHRLA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_case_temp
    {
        public int ID { get; set; }
        public Nullable<int> Case_ID { get; set; }
        public Nullable<int> CaseHistoryLogID { get; set; }
        public string Case_Code { get; set; }
        public Nullable<System.DateTime> Case_DateTime { get; set; }
        public Nullable<int> Case_Type_Id { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public Nullable<int> Case_Registeration_Type_Id { get; set; }
        public Nullable<int> Attachment_Count { get; set; }
        public Nullable<bool> Is_Submitted { get; set; }
        public Nullable<int> Current_Status_ID { get; set; }
        public Nullable<int> Call_ID { get; set; }
        public Nullable<int> Linked_Case_ID { get; set; }
        public string Case_Reference_Person { get; set; }
        public Nullable<int> Approval_Level { get; set; }
        public string Client_Name { get; set; }
        public string Client_Contact { get; set; }
        public string Client_CNIC { get; set; }
        public Nullable<System.DateTime> Followup_Date { get; set; }
        public Nullable<int> Branch_ID { get; set; }
        public Nullable<int> CounselorId { get; set; }
    
        public virtual tbl_Branch tbl_Branch { get; set; }
        public virtual tbl_Case tbl_Case { get; set; }
        public virtual tbl_Case_History_Log tbl_Case_History_Log { get; set; }
        public virtual tbl_Case_Registeration_Types tbl_Case_Registeration_Types { get; set; }
    }
}
