//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHRLA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Councelling_Sessions
    {
        public int ID { get; set; }
        public Nullable<int> Case_ID { get; set; }
        public Nullable<int> Counceller_ID { get; set; }
        public Nullable<int> Session_Duration_In_Mins { get; set; }
        public Nullable<System.DateTime> Session_Datetime { get; set; }
        public string Session_Details { get; set; }
        public Nullable<bool> Is_Submitted { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    
        public virtual tbl_Case tbl_Case { get; set; }
    }
}
