//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHRLA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Case_Fields_Options
    {
        public int ID { get; set; }
        public Nullable<int> Case_Field_ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    
        public virtual tbl_Case_Fields tbl_Case_Fields { get; set; }
    }
}
