//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHRLA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Role_Pages
    {
        public int ID { get; set; }
        public int Role_ID { get; set; }
        public int Page_ID { get; set; }
    
        public virtual tbl_Pages tbl_Pages { get; set; }
        public virtual tbl_Role tbl_Role { get; set; }
    }
}
