//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHRLA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User_Branch
    {
        public int ID { get; set; }
        public long User_ID { get; set; }
        public int Branch_ID { get; set; }
    
        public virtual tbl_Branch tbl_Branch { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
