//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHRLA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Meetings
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Start_Datetime { get; set; }
        public Nullable<System.DateTime> End_Datetime { get; set; }
        public string Location_Descp { get; set; }
        public Nullable<int> City_Id { get; set; }
        public string Description { get; set; }
        public string Followup_Notes { get; set; }
        public string Participants_Details { get; set; }
        public Nullable<int> Case_ID { get; set; }
        public string Meeting_Initiated_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual tbl_City tbl_City { get; set; }
    }
}
