//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHRLA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Case_History_Log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Case_History_Log()
        {
            this.tbl_Case_Data_temp = new HashSet<tbl_Case_Data_temp>();
            this.tbl_case_temp = new HashSet<tbl_case_temp>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Case_ID { get; set; }
        public string Old_Data { get; set; }
        public string New_Data { get; set; }
        public Nullable<int> Approval1_User { get; set; }
        public Nullable<System.DateTime> Approval1_Datetime { get; set; }
        public string Approval1_Comments { get; set; }
        public Nullable<int> Approval2_User { get; set; }
        public Nullable<System.DateTime> Approval2_Datetime { get; set; }
        public string Approval2_Comments { get; set; }
    
        public virtual tbl_Case tbl_Case { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Case_Data_temp> tbl_Case_Data_temp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_case_temp> tbl_case_temp { get; set; }
    }
}
