//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHRLA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Calls
    {
        public int ID { get; set; }
        public string Caller_Number { get; set; }
        public string Caller_Name { get; set; }
        public Nullable<int> Operator_ID { get; set; }
        public Nullable<System.DateTime> Call_Start_DateTime { get; set; }
        public Nullable<System.DateTime> Call_End_DateTime { get; set; }
        public Nullable<int> Call_Duration_In_Mins { get; set; }
        public string Caller_Longitude { get; set; }
        public string Caller_Latitude { get; set; }
        public Nullable<int> City_ID { get; set; }
        public Nullable<bool> Is_Received { get; set; }
        public string Operator_Descp { get; set; }
    
        public virtual tbl_City tbl_City { get; set; }
    }
}
