//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHRLA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserLog
    {
        public int ID { get; set; }
        public string Entity_Type { get; set; }
        public Nullable<int> Entity_ID { get; set; }
        public Nullable<System.DateTime> Action_Timestamp { get; set; }
        public string Description { get; set; }
        public string Action_Name { get; set; }
        public Nullable<int> Action_User_ID { get; set; }
    }
}
