//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHRLA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Case()
        {
            this.tbl_Case_Data = new HashSet<tbl_Case_Data>();
            this.tbl_Case_Data_temp = new HashSet<tbl_Case_Data_temp>();
            this.tbl_Case_History_Log = new HashSet<tbl_Case_History_Log>();
            this.tbl_Case_Referral = new HashSet<tbl_Case_Referral>();
            this.tbl_Case_Tags = new HashSet<tbl_Case_Tags>();
            this.tbl_case_temp = new HashSet<tbl_case_temp>();
            this.tbl_Councelling_Sessions = new HashSet<tbl_Councelling_Sessions>();
        }
    
        public int ID { get; set; }
        public string Case_Code { get; set; }
        public Nullable<System.DateTime> Case_DateTime { get; set; }
        public Nullable<int> Case_Type_Id { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public Nullable<int> Case_Registeration_Type_Id { get; set; }
        public Nullable<int> Attachment_Count { get; set; }
        public Nullable<bool> Is_Submitted { get; set; }
        public Nullable<int> Current_Status_ID { get; set; }
        public Nullable<int> Call_ID { get; set; }
        public Nullable<int> Linked_Case_ID { get; set; }
        public string Case_Reference_Person { get; set; }
        public Nullable<int> Approval_Level { get; set; }
        public string Client_Name { get; set; }
        public string Client_Contact { get; set; }
        public string Client_CNIC { get; set; }
        public Nullable<System.DateTime> Followup_Date { get; set; }
        public Nullable<int> Branch_ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CounselorId { get; set; }
    
        public virtual tbl_Branch tbl_Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Case_Data> tbl_Case_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Case_Data_temp> tbl_Case_Data_temp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Case_History_Log> tbl_Case_History_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Case_Referral> tbl_Case_Referral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Case_Tags> tbl_Case_Tags { get; set; }
        public virtual tbl_Case_Types tbl_Case_Types { get; set; }
        public virtual tbl_Case_Registeration_Types tbl_Case_Registeration_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_case_temp> tbl_case_temp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Councelling_Sessions> tbl_Councelling_Sessions { get; set; }
    }
}
