//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHRLA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Email_Users
    {
        public int ID { get; set; }
        public int Email_Setup_ID { get; set; }
        public long User_ID { get; set; }
    
        public virtual tbl_Email_Setup tbl_Email_Setup { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
